### ISSUE TITLE
H1 & H2 always create H5 & H6

### ISSUE THREAD

**Issue by good-idea** [storypioneers/kirby-wysiwyg#14]
I'm having a problem with the H1 and H2 buttons in the editor - no matter how I mess around with the config or blueprint settings, they always give me `##### this` and `###### this`

I'm having the same issue in several installations of kirby. Anything I can do?

**Comment by janstieler** [comment]
+1

**Comment by rgalton** [comment]
I also had this problem but solved it by hyphenating 'first-header' and 'second-header' in my blueprints, e.g.:

```
fields:
    richtext:
        label: Text
        type:  wysiwyg
        first-header: h2
        second-header: h3
```
