### ISSUE TITLE
Make "buttons" option settable from blueprints

### ISSUE THREAD

**Issue by JonasDoebertin** [storypioneers/kirby-wysiwyg#3]
The `buttons` configuration option, which determines which buttons will be shown in the editors toolbar should be settable per field from the blueprints to allow for a more flexible usage.

```
fields:
  mytext:
    label: Medium Editor Field
    type:  medium
    buttons:
      - bold
      - italic
      - ...
```
