### ISSUE TITLE
Dynamically style Header 1& Header 2 headings

### ISSUE THREAD

**Issue by JonasDoebertin** [storypioneers/kirby-wysiwyg#8]
Currently, the headline styles are defined like this:

``` css
.wysiwyg-editor h2 {
    font-size: 1.6em;
    font-weight: bold;
    margin-bottom: 1em;
}

.wysiwyg-editor h3 {
    font-size: 1.2em;
    font-weight: bold;
    margin-bottom: 1em;
}
```

While this is fine in most cases, users may specify different HTML heading tags to be used instead. To compensate for this, these styles should be injected dynamically.
